name: Public Films
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48215
title: Public Films
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#FEFEFE'
    - '#2A2B24'
    - '#93948F'
    - '#540206'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.694337
  rhythmicContrast: 0.75
purpose: []
