name: Public Films
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5352587141096592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#2a2b24'
    - '#93948f'
    - '#540206'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.6943372059613466
  rhythmicContrast: 0.25
purpose: []
