name: Public Films
favicon: null
layout_spectrum: 0.4919584693852812
typography_spectrum: 0.5352587141096592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#cc0b0c'
    - '#333333'
    - '#a7a7a7'
  brandStrength: 0.7202704288065434
  lightness: 0.4715560870245099
  saturation: 0.6943372059613466
  rhythmicContrast: 0.7320668972097337
purpose: []
