analytics: {}
color:
  brandColors:
    - '#000000'
    - '#FEFEFE'
    - '#2A2B24'
    - '#93948F'
    - '#540206'
  brandStrength: 0.8125
  lightness: 0.5625
  rhythmicContrast: 0.75
  saturation: 0.6943372059613466
cta: {}
layout_spectrum: 1
name: Public Films
opengraph: {}
purpose: []
typography_spectrum: 0.48215
